# REGISTER USER
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "coopercoote",
  "email": "ccoote@gmail.com",
  "password": "cg123"
}
########

# REGISTER USER
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "coopercoote",
  "password": "cg123"
}
